# Generated by Django 4.2.2 on 2023-10-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Date_of_Birth', models.DateField()),
            ],
        ),
    ]
